version: '3.8'

services:
  dashboard:
    image: ghcr.io/aaacoder-ds/services-dashboard:main
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3