version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      # Use a shell form so we can fall back to curl if present
      test: ["CMD-SHELL", "command -v curl >/dev/null 2>&1 && curl -fs http://localhost/health || (command -v wget >/dev/null 2>&1 && wget -qO- http://localhost/health)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80" 